### ISSUE TITLE
The library 'package:star_rating/star_rating.dart' is legacy, and should not be imported into a null safe library. Try migrating the imported library.

### ISSUE THREAD

**Issue by abbas-25** [kranfix/flutter_star_rating#1]
If the author can't update to sound null safety for any reason, I'll be happy to do it. However, do reply if you are available to accept the pull request.

Thanks

**Comment by kranfix** [comment]
Sorry for late response.

Please, send your PR. I want to update the code, but I have no enough time. I would appreciate your contribution.

**Comment by kranfix** [comment]
I migrated the library to null-safety

**Comment by kranfix** [comment]
The package is migrated to null-safety.
